development:
  adapter: postgresql
  encoding: utf8
  database: troop_website_dev
  pool: 5
  username:
  password:

test: &test
  adapter: postgresql
  encoding: utf8
  database: troop_website_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  database: troop_website
  pool: 5
  timeout: 5000

cucumber:
  <<: *test
